export const yemenGovernorates = [
  {
    id: 'sanaa_city',
    nameAr: 'أمانة العاصمة',
    nameEn: 'Amanat Al Asimah',
    districts: [
      { id: 'old_city', nameAr: 'صنعاء القديمة', nameEn: 'Old City' },
      { id: 'al_wahdah', nameAr: 'الوحدة', nameEn: 'Al Wahdah' },
      { id: 'al_sabeen', nameAr: 'السبعين', nameEn: 'Al Sabeen' },
      { id: 'al_safiyah', nameAr: 'الصافية', nameEn: 'Al Safiyah' },
      { id: 'al_tahrir', nameAr: 'التحرير', nameEn: 'Al Tahrir' },
      { id: 'al_thawrah', nameAr: 'الثورة', nameEn: 'Al Thawrah' },
      { id: 'az_zal', nameAr: 'آزال', nameEn: 'Az Zal' },
      { id: 'bani_al_harith', nameAr: 'بني الحارث', nameEn: 'Bani Al Harith' },
      { id: 'maain', nameAr: 'معين', nameEn: 'Maain' },
      { id: 'shuaub', nameAr: 'شعوب', nameEn: 'Shuaub' }
    ]
  },
  {
    id: 'sanaa',
    nameAr: 'صنعاء',
    nameEn: 'Sana\'a',
    districts: [
      { id: 'al_haymah_ad_dakhiliyah', nameAr: 'الحيمة الداخلية', nameEn: 'Al Haymah Ad Dakhiliyah' },
      { id: 'al_haymah_al_kharijiyah', nameAr: 'الحيمة الخارجية', nameEn: 'Al Haymah Al Kharijiyah' },
      { id: 'al_husn', nameAr: 'الحصن', nameEn: 'Al Husn' },
      { id: 'arhab', nameAr: 'أرحب', nameEn: 'Arhab' },
      { id: 'atyal', nameAr: 'الطيال', nameEn: 'Atyal' },
      { id: 'bani_dhabyan', nameAr: 'بني ضبيان', nameEn: 'Bani Dhabyan' },
      { id: 'bani_hushaysh', nameAr: 'بني حشيش', nameEn: 'Bani Hushaysh' },
      { id: 'bani_matar', nameAr: 'بني مطر', nameEn: 'Bani Matar' },
      { id: 'bilad_ar_rus', nameAr: 'بلاد الروس', nameEn: 'Bilad Ar Rus' },
      { id: 'hamdan', nameAr: 'همدان', nameEn: 'Hamdan' },
      { id: 'jihanah', nameAr: 'جحانة', nameEn: 'Jihanah' },
      { id: 'khawlan', nameAr: 'خولان', nameEn: 'Khawlan' },
      { id: 'manakhah', nameAr: 'مناخة', nameEn: 'Manakhah' },
      { id: 'nihm', nameAr: 'نهم', nameEn: 'Nihm' },
      { id: 'saafan', nameAr: 'صعفان', nameEn: 'Saafan' },
      { id: 'sanhan', nameAr: 'سنحان وبني بهلول', nameEn: 'Sanhan' }
    ]
  },
  {
    id: 'aden',
    nameAr: 'عدن',
    nameEn: 'Aden',
    districts: [
      { id: 'craiter', nameAr: 'كريتر', nameEn: 'Craiter' },
      { id: 'dar_sad', nameAr: 'دار سعد', nameEn: 'Dar Sad' },
      { id: 'al_mansura', nameAr: 'المنصورة', nameEn: 'Al Mansura' },
      { id: 'al_mualla', nameAr: 'المعلا', nameEn: 'Al Mualla' },
      { id: 'ash_shaikh_outhman', nameAr: 'الشيخ عثمان', nameEn: 'Ash Shaikh Outhman' },
      { id: 'al_buraiqeh', nameAr: 'البريقة', nameEn: 'Al Buraiqeh' },
      { id: 'at_tawahi', nameAr: 'التواهي', nameEn: 'At Tawahi' },
      { id: 'khur_maksar', nameAr: 'خور مكسر', nameEn: 'Khur Maksar' }
    ]
  },
  {
    id: 'taiz',
    nameAr: 'تعز',
    nameEn: 'Taiz',
    districts: [
      { id: 'al_qahirah', nameAr: 'القاهرة', nameEn: 'Al Qahirah' },
      { id: 'salh', nameAr: 'صالة', nameEn: 'Salh' },
      { id: 'al_mudhaffar', nameAr: 'المظفر', nameEn: 'Al Mudhaffar' },
      { id: 'al_makha', nameAr: 'المخاء', nameEn: 'Al Makha' },
      { id: 'al_maafir', nameAr: 'المعافر', nameEn: 'Al Maafir' },
      { id: 'al_mawasit', nameAr: 'المواسط', nameEn: 'Al Mawasit' },
      { id: 'al_misrakh', nameAr: 'المسراخ', nameEn: 'Al Misrakh' },
      { id: 'al_waziayah', nameAr: 'الوازعية', nameEn: 'Al Waziayah' },
      { id: 'as_silw', nameAr: 'الصلو', nameEn: 'As Silw' },
      { id: 'ash_shumayatayn', nameAr: 'الشمايتين', nameEn: 'Ash Shumayatayn' },
      { id: 'at_taizziyah', nameAr: 'التعزية', nameEn: 'At Taizziyah' },
      { id: 'dhubab', nameAr: 'ذباب', nameEn: 'Dhubab' },
      { id: 'dimnat_khadir', nameAr: 'دمنة خدير', nameEn: 'Dimnat Khadir' },
      { id: 'hayfan', nameAr: 'حيفان', nameEn: 'Hayfan' },
      { id: 'jabal_habashy', nameAr: 'جبل حبشي', nameEn: 'Jabal Habashy' },
      { id: 'maqbanah', nameAr: 'مقبنة', nameEn: 'Maqbanah' },
      { id: 'mashraah_wa_hadnan', nameAr: 'مشرعة وحدنان', nameEn: 'Mashraah Wa Hadnan' },
      { id: 'mawiyah', nameAr: 'ماوية', nameEn: 'Mawiyah' },
      { id: 'mawza', nameAr: 'موزع', nameEn: 'Mawza' },
      { id: 'sabr_al_mawadam', nameAr: 'صبر الموادم', nameEn: 'Sabr Al Mawadam' },
      { id: 'samia', nameAr: 'سامع', nameEn: 'Samia' },
      { id: 'sharaab_ar_rawnah', nameAr: 'شرعب الرونة', nameEn: 'Sharaab Ar Rawnah' },
      { id: 'sharaab_as_salam', nameAr: 'شرعب السلام', nameEn: 'Sharaab As Salam' }
    ]
  },
  {
    id: 'al_hudaydah',
    nameAr: 'الحديدة',
    nameEn: 'Al Hudaydah',
    districts: [
      { id: 'al_hali', nameAr: 'الحالي', nameEn: 'Al Hali' },
      { id: 'al_hawak', nameAr: 'الحوك', nameEn: 'Al Hawak' },
      { id: 'al_mina', nameAr: 'الميناء', nameEn: 'Al Mina' },
      { id: 'ad_durayhimi', nameAr: 'الدريهمي', nameEn: 'Ad Durayhimi' },
      { id: 'al_garrahi', nameAr: 'الجراحي', nameEn: 'Al Garrahi' },
      { id: 'al_hajjaylah', nameAr: 'الحجيلة', nameEn: 'Al Hajjaylah' },
      { id: 'al_khawkhah', nameAr: 'الخوخة', nameEn: 'Al Khawkhah' },
      { id: 'al_mansuriyah', nameAr: 'المنصورية', nameEn: 'Al Mansuriyah' },
      { id: 'al_marawi', nameAr: 'المراوعة', nameEn: 'Al Marawi' },
      { id: 'al_mighlaf', nameAr: 'المغلاف', nameEn: 'Al Mighlaf' },
      { id: 'al_munirah', nameAr: 'المنيرة', nameEn: 'Al Munirah' },
      { id: 'al_qanawis', nameAr: 'القناوص', nameEn: 'Al Qanawis' },
      { id: 'alluheyah', nameAr: 'اللحية', nameEn: 'Alluheyah' },
      { id: 'as_salif', nameAr: 'الصليف', nameEn: 'As Salif' },
      { id: 'as_sukhnah', nameAr: 'السخنة', nameEn: 'As Sukhnah' },
      { id: 'at_tuhayat', nameAr: 'التحيتا', nameEn: 'At Tuhayat' },
      { id: 'az_zaydiyah', nameAr: 'الزيدية', nameEn: 'Az Zaydiyah' },
      { id: 'az_zuhrah', nameAr: 'الزهرة', nameEn: 'Az Zuhrah' },
      { id: 'bajil', nameAr: 'باجل', nameEn: 'Bajil' },
      { id: 'bayt_al_faqih', nameAr: 'بيت الفقيه', nameEn: 'Bayt Al Faqih' },
      { id: 'bura', nameAr: 'برع', nameEn: 'Bura' },
      { id: 'hays', nameAr: 'حيس', nameEn: 'Hays' },
      { id: 'jabal_ras', nameAr: 'جبل رأس', nameEn: 'Jabal Ras' },
      { id: 'kamaran', nameAr: 'كمران', nameEn: 'Kamaran' },
      { id: 'zabid', nameAr: 'زبيد', nameEn: 'Zabid' }
    ]
  },
  {
    id: 'ibb',
    nameAr: 'إب',
    nameEn: 'Ibb',
    districts: [
      { id: 'al_dhihar', nameAr: 'الظهار', nameEn: 'Al Dhihar' },
      { id: 'al_mashannah', nameAr: 'المشنة', nameEn: 'Al Mashannah' },
      { id: 'al_udayn', nameAr: 'العدين', nameEn: 'Al Udayn' },
      { id: 'an_nadirah', nameAr: 'النادرة', nameEn: 'An Nadirah' },
      { id: 'ar_radmah', nameAr: 'الرضمة', nameEn: 'Ar Radmah' },
      { id: 'as_sabrah', nameAr: 'السبرة', nameEn: 'As Sabrah' },
      { id: 'as_saddah', nameAr: 'السدة', nameEn: 'As Saddah' },
      { id: 'as_sayyani', nameAr: 'السياني', nameEn: 'As Sayyani' },
      { id: 'ash_shair', nameAr: 'الشعر', nameEn: 'Ash Shair' },
      { id: 'baadan', nameAr: 'بعدان', nameEn: 'Baadan' },
      { id: 'dhi_as_sufal', nameAr: 'ذي السفال', nameEn: 'Dhi As Sufal' },
      { id: 'far_al_udayn', nameAr: 'فرع العدين', nameEn: 'Far Al Udayn' },
      { id: 'habil_jabr', nameAr: 'حبيش', nameEn: 'Hubaysh' },
      { id: 'hazm_al_udayn', nameAr: 'حزم العدين', nameEn: 'Hazm Al Udayn' },
      { id: 'ibb', nameAr: 'إب', nameEn: 'Ibb' },
      { id: 'jiblha', nameAr: 'جبلة', nameEn: 'Jiblah' },
      { id: 'mudhaykhirah', nameAr: 'مذيخرة', nameEn: 'Mudhaykhirah' },
      { id: 'al_makhadir', nameAr: 'المخادر', nameEn: 'Al Makhadir' },
      { id: 'yarim', nameAr: 'يريم', nameEn: 'Yarim' },
      { id: 'al_qafr', nameAr: 'الفرع', nameEn: 'Al Qafr' }
    ]
  },
  {
    id: 'hadhramaut',
    nameAr: 'حضرموت',
    nameEn: 'Hadhramaut',
    districts: [
      { id: 'al_mukalla', nameAr: 'المكلا', nameEn: 'Al Mukalla' },
      { id: 'al_mukalla_city', nameAr: 'مدينة المكلا', nameEn: 'Al Mukalla City' },
      { id: 'sayun', nameAr: 'سيئون', nameEn: 'Sayun' },
      { id: 'tarim', nameAr: 'تريم', nameEn: 'Tarim' },
      { id: 'ash_shihr', nameAr: 'الشحر', nameEn: 'Ash Shihr' },
      { id: 'ghayl_bawazir', nameAr: 'غيل باوزير', nameEn: 'Ghayl Bawazir' },
      { id: 'shibam', nameAr: 'شبام', nameEn: 'Shibam' },
      { id: 'al_qatn', nameAr: 'القطن', nameEn: 'Al Qatn' },
      { id: 'ammd', nameAr: 'عمد', nameEn: 'Ammd' },
      { id: 'dawan', nameAr: 'دوعن', nameEn: 'Dawan' },
      { id: 'wady_al_ayn', nameAr: 'وادي العين', nameEn: 'Wady Al Ayn' },
      { id: 'rakhyah', nameAr: 'رخية', nameEn: 'Rakhyah' },
      { id: 'huraidhah', nameAr: 'حريضة', nameEn: 'Huraidhah' },
      { id: 'haghr_as_sayar', nameAr: 'حجر الصيعر', nameEn: 'Haghr As Sayar' },
      { id: 'zamakh_wa_manwakh', nameAr: 'زمخ ومنوخ', nameEn: 'Zamakh Wa Manwakh' },
      { id: 'al_abr', nameAr: 'العبر', nameEn: 'Al Abr' },
      { id: 'thamud', nameAr: 'ثمود', nameEn: 'Thamud' },
      { id: 'rumah', nameAr: 'رماه', nameEn: 'Rumah' },
      { id: 'qaf_al_awamir', nameAr: 'قف العوامر', nameEn: 'Qaf Al Awamir' },
      { id: 'as_sawm', nameAr: 'السوم', nameEn: 'As Sawm' },
      { id: 'ad_dis', nameAr: 'الديس', nameEn: 'Ad Dis' },
      { id: 'ar_raydah_wa_qusayar', nameAr: 'الريدة وقصيعر', nameEn: 'Ar Raydah Wa Qusayar' },
      { id: 'yabuth', nameAr: 'يبعث', nameEn: 'Yabuth' },
      { id: 'hajar', nameAr: 'حجر', nameEn: 'Hajar' },
      { id: 'broum_mayfaah', nameAr: 'بروم ميفعة', nameEn: 'Broum Mayfaah' },
      { id: 'ghayl_bin_yamin', nameAr: 'غيل بن يمين', nameEn: 'Ghayl Bin Yamin' },
      { id: 'sah', nameAr: 'ساه', nameEn: 'Sah' }
    ]
  },
  {
    id: 'hajjah',
    nameAr: 'حجة',
    nameEn: 'Hajjah',
    districts: [
      { id: 'hajjah_city', nameAr: 'مدينة حجة', nameEn: 'Hajjah City' },
      { id: 'hajjah', nameAr: 'حجة', nameEn: 'Hajjah' },
      { id: 'abs', nameAr: 'عبس', nameEn: 'Abs' },
      { id: 'aflah_al_yaman', nameAr: 'أفلح اليمن', nameEn: 'Aflah Al Yaman' },
      { id: 'aflah_ash_shawm', nameAr: 'أفلح الشام', nameEn: 'Aflah Ash Shawm' },
      { id: 'al_jamimah', nameAr: 'الجميمة', nameEn: 'Al Jamimah' },
      { id: 'al_mabayn', nameAr: 'المبين', nameEn: 'Al Mabayn' },
      { id: 'al_maghrabah', nameAr: 'المغربة', nameEn: 'Al Maghrabah' },
      { id: 'al_mahabishah', nameAr: 'المحابشة', nameEn: 'Al Mahabishah' },
      { id: 'al_miftah', nameAr: 'المفتاح', nameEn: 'Al Miftah' },
      { id: 'ash_shaghadirah', nameAr: 'الشغادرة', nameEn: 'Ash Shaghadirah' },
      { id: 'ash_shahil', nameAr: 'الشاهل', nameEn: 'Ash Shahil' },
      { id: 'aslem', nameAr: 'أسلم', nameEn: 'Aslem' },
      { id: 'bakil_al_mir', nameAr: 'بكيل المير', nameEn: 'Bakil Al Mir' },
      { id: 'bani_al_awam', nameAr: 'بني العوام', nameEn: 'Bani Al Awam' },
      { id: 'bani_qais', nameAr: 'بني قيس', nameEn: 'Bani Qais' },
      { id: 'harad', nameAr: 'حرض', nameEn: 'Harad' },
      { id: 'hayran', nameAr: 'حيران', nameEn: 'Hayran' },
      { id: 'khayran_al_muharraq', nameAr: 'خيران المحرق', nameEn: 'Khayran Al Muharraq' },
      { id: 'kuaydinah', nameAr: 'كعيدنة', nameEn: 'Kuaydinah' },
      { id: 'kuhlan_affar', nameAr: 'كحلان عفار', nameEn: 'Kuhlan Affar' },
      { id: 'kuhlan_ash_sharaf', nameAr: 'كحلان الشرف', nameEn: 'Kuhlan Ash Sharaf' },
      { id: 'kushar', nameAr: 'كشر', nameEn: 'Kushar' },
      { id: 'mabyan', nameAr: 'مبين', nameEn: 'Mabyan' },
      { id: 'midi', nameAr: 'ميدي', nameEn: 'Midi' },
      { id: 'mustaba', nameAr: 'مستباء', nameEn: 'Mustaba' },
      { id: 'najarah', nameAr: 'نجرة', nameEn: 'Najarah' },
      { id: 'qafl_shamir', nameAr: 'قفل شمر', nameEn: 'Qafl Shamir' },
      { id: 'qarah', nameAr: 'قارة', nameEn: 'Qarah' },
      { id: 'sharas', nameAr: 'شرس', nameEn: 'Sharas' },
      { id: 'wadhrah', nameAr: 'وضرة', nameEn: 'Wadhrah' },
      { id: 'washhah', nameAr: 'وشحة', nameEn: 'Washhah' }
    ]
  },
  {
    id: 'dhamar',
    nameAr: 'ذمار',
    nameEn: 'Dhamar',
    districts: [
      { id: 'dhamar_city', nameAr: 'مدينة ذمار', nameEn: 'Dhamar City' },
      { id: 'al_hada', nameAr: 'الحداء', nameEn: 'Al Hada' },
      { id: 'al_manar', nameAr: 'المنار', nameEn: 'Al Manar' },
      { id: 'ans', nameAr: 'عنس', nameEn: 'Ans' },
      { id: 'dawran_anes', nameAr: 'ضوران آنس', nameEn: 'Dawran Anes' },
      { id: 'jabal_ash_sharq', nameAr: 'جبل الشرق', nameEn: 'Jabal Ash Sharq' },
      { id: 'jahran', nameAr: 'جهران', nameEn: 'Jahran' },
      { id: 'maghirib_ans', nameAr: 'مغرب عنس', nameEn: 'Maghirib Ans' },
      { id: 'mayfaat_ans', nameAr: 'ميفعة عنس', nameEn: 'Mayfaat Ans' },
      { id: 'utmah', nameAr: 'عتمة', nameEn: 'Utmah' },
      { id: 'wusab_al_ali', nameAr: 'وصاب العالي', nameEn: 'Wusab Al Ali' },
      { id: 'wusab_as_safil', nameAr: 'وصاب السافل', nameEn: 'Wusab As Safil' }
    ]
  },
  {
    id: 'sadah',
    nameAr: 'صعدة',
    nameEn: 'Sa\'dah',
    districts: [
      { id: 'sadah', nameAr: 'صعدة', nameEn: 'Sadah' },
      { id: 'al_dhaher', nameAr: 'الظاهر', nameEn: 'Al Dhaher' },
      { id: 'al_hashwah', nameAr: 'الحشوة', nameEn: 'Al Hashwah' },
      { id: 'as_safra', nameAr: 'الصفراء', nameEn: 'As Safra' },
      { id: 'baqim', nameAr: 'باقم', nameEn: 'Baqim' },
      { id: 'dammaj', nameAr: 'دماج', nameEn: 'Dammaj' },
      { id: 'ghamar', nameAr: 'غمر', nameEn: 'Ghamar' },
      { id: 'haydan', nameAr: 'حيدان', nameEn: 'Haydan' },
      { id: 'kitaf_wa_al_boqa', nameAr: 'كتاف والبقع', nameEn: 'Kitaf Wa Al Boqa' },
      { id: 'majz', nameAr: 'مجز', nameEn: 'Majz' },
      { id: 'monabbih', nameAr: 'منبه', nameEn: 'Monabbih' },
      { id: 'qatabir', nameAr: 'قطابر', nameEn: 'Qatabir' },
      { id: 'razih', nameAr: 'رازح', nameEn: 'Razih' },
      { id: 'sahar', nameAr: 'سحار', nameEn: 'Sahar' },
      { id: 'saqayn', nameAr: 'ساقين', nameEn: 'Saqayn' },
      { id: 'shadaa', nameAr: 'شداء', nameEn: 'Shadaa' }
    ]
  },
  {
    id: 'al_mahwit',
    nameAr: 'المحويت',
    nameEn: 'Al Mahwit',
    districts: [
      { id: 'al_mahwit_city', nameAr: 'مدينة المحويت', nameEn: 'Al Mahwit City' },
      { id: 'al_khabt', nameAr: 'الخبت', nameEn: 'Al Khabt' },
      { id: 'al_mahwit', nameAr: 'المحويت', nameEn: 'Al Mahwit' },
      { id: 'ar_rujum', nameAr: 'الرجم', nameEn: 'Ar Rujum' },
      { id: 'at_tawilah', nameAr: 'الطويلة', nameEn: 'At Tawilah' },
      { id: 'bani_sad', nameAr: 'بني سعد', nameEn: 'Bani Sad' },
      { id: 'hufash', nameAr: 'حفاش', nameEn: 'Hufash' },
      { id: 'milhan', nameAr: 'ملحان', nameEn: 'Milhan' },
      { id: 'shibam_kawkaban', nameAr: 'شبام كوكبان', nameEn: 'Shibam Kawkaban' }
    ]
  },
  {
    id: 'amran',
    nameAr: 'عمران',
    nameEn: 'Amran',
    districts: [
      { id: 'amran', nameAr: 'عمران', nameEn: 'Amran' },
      { id: 'al_ashah', nameAr: 'العشة', nameEn: 'Al Ashah' },
      { id: 'al_madan', nameAr: 'المدان', nameEn: 'Al Madan' },
      { id: 'al_qaflah', nameAr: 'القفلة', nameEn: 'Al Qaflah' },
      { id: 'as_sawd', nameAr: 'السود', nameEn: 'As Sawd' },
      { id: 'as_sudah', nameAr: 'السودة', nameEn: 'As Sudah' },
      { id: 'bani_surim', nameAr: 'بني صريم', nameEn: 'Bani Surim' },
      { id: 'dhi_bin', nameAr: 'ذيبين', nameEn: 'Dhi Bin' },
      { id: 'harf_sufyan', nameAr: 'حرف سفيان', nameEn: 'Harf Sufyan' },
      { id: 'huth', nameAr: 'حوث', nameEn: 'Huth' },
      { id: 'iyal_surayh', nameAr: 'عيال سريح', nameEn: 'Iyal Surayh' },
      { id: 'jabal_iyaz', nameAr: 'جبل عيال يزيد', nameEn: 'Jabal Iyal Yazid' },
      { id: 'khamir', nameAr: 'خمر', nameEn: 'Khamir' },
      { id: 'kharif', nameAr: 'خارف', nameEn: 'Kharif' },
      { id: 'maswar', nameAr: 'مسور', nameEn: 'Maswar' },
      { id: 'raydah', nameAr: 'ريدة', nameEn: 'Raydah' },
      { id: 'shahara', nameAr: 'شهارة', nameEn: 'Shaharah' },
      { id: 'suwayr', nameAr: 'صوير', nameEn: 'Suwayr' },
      { id: 'thula', nameAr: 'ثلاء', nameEn: 'Thula' }
    ]
  },
  {
    id: 'al_dhalee',
    nameAr: 'الضالع',
    nameEn: 'Al Dhale\'e',
    districts: [
      { id: 'al_dhalee', nameAr: 'الضالع', nameEn: 'Al Dhalee' },
      { id: 'al_azariq', nameAr: 'الأزارق', nameEn: 'Al Azariq' },
      { id: 'al_husha', nameAr: 'الحشاء', nameEn: 'Al Husha' },
      { id: 'al_husayn', nameAr: 'الحصين', nameEn: 'Al Husayn' },
      { id: 'ash_shuayb', nameAr: 'الشعيب', nameEn: 'Ash Shuayb' },
      { id: 'damt', nameAr: 'دمت', nameEn: 'Damt' },
      { id: 'jahaf', nameAr: 'جحاف', nameEn: 'Jahaf' },
      { id: 'juban', nameAr: 'جبن', nameEn: 'Juban' },
      { id: 'qaatabah', nameAr: 'قعطبة', nameEn: 'Qaatabah' }
    ]
  },
  {
    id: 'lahij',
    nameAr: 'لحج',
    nameEn: 'Lahij',
    districts: [
      { id: 'al_hawtah', nameAr: 'الحوطة', nameEn: 'Al Hawtah' },
      { id: 'al_had', nameAr: 'الحد', nameEn: 'Al Had' },
      { id: 'al_madaribah_wa_al_arah', nameAr: 'المضاربة والعارة', nameEn: 'Al Madaribah Wa Al Arah' },
      { id: 'al_maflahy', nameAr: 'المفلحي', nameEn: 'Al Maflahy' },
      { id: 'al_maqatirah', nameAr: 'المقاطرة', nameEn: 'Al Maqatirah' },
      { id: 'al_milah', nameAr: 'الملاح', nameEn: 'Al Milah' },
      { id: 'al_musaymir', nameAr: 'المسيمير', nameEn: 'Al Musaymir' },
      { id: 'al_qabbaytah', nameAr: 'القبيطة', nameEn: 'Al Qabbaytah' },
      { id: 'habil_jabr', nameAr: 'حبيل جبر', nameEn: 'Habil Jabr' },
      { id: 'halimayn', nameAr: 'حالمين', nameEn: 'Halimayn' },
      { id: 'radfan', nameAr: 'ردفان', nameEn: 'Radfan' },
      { id: 'tuban', nameAr: 'تبن', nameEn: 'Tuban' },
      { id: 'tur_al_bahah', nameAr: 'طور الباحة', nameEn: 'Tur Al Bahah' },
      { id: 'yafea', nameAr: 'يافع', nameEn: 'Yafea' },
      { id: 'yahr', nameAr: 'يهر', nameEn: 'Yahr' }
    ]
  },
  {
    id: 'abyan',
    nameAr: 'أبين',
    nameEn: 'Abyan',
    districts: [
      { id: 'zinjibar', nameAr: 'زنجبار', nameEn: 'Zinjibar' },
      { id: 'ahwar', nameAr: 'أحور', nameEn: 'Ahwar' },
      { id: 'al_mahfad', nameAr: 'المحفد', nameEn: 'Al Mahfad' },
      { id: 'al_wadea', nameAr: 'الوضيع', nameEn: 'Al Wadea' },
      { id: 'jayshan', nameAr: 'جيشان', nameEn: 'Jayshan' },
      { id: 'khanfir', nameAr: 'خنفر', nameEn: 'Khanfir' },
      { id: 'lawdar', nameAr: 'لودر', nameEn: 'Lawdar' },
      { id: 'mudiyah', nameAr: 'مودية', nameEn: 'Mudiyah' },
      { id: 'rasad', nameAr: 'رصد', nameEn: 'Rasad' },
      { id: 'sarar', nameAr: 'سرار', nameEn: 'Sarar' },
      { id: 'sibah', nameAr: 'سباح', nameEn: 'Sibah' }
    ]
  },
  {
    id: 'shabwah',
    nameAr: 'شبوة',
    nameEn: 'Shabwah',
    districts: [
      { id: 'ataq', nameAr: 'عتق', nameEn: 'Ataq' },
      { id: 'ayn', nameAr: 'عين', nameEn: 'Ayn' },
      { id: 'al_talh', nameAr: 'الطلح', nameEn: 'Al Talh' },
      { id: 'ar_rawdah', nameAr: 'الروضة', nameEn: 'Ar Rawdah' },
      { id: 'arma', nameAr: 'عرماء', nameEn: 'Arma' },
      { id: 'as_said', nameAr: 'الصعيد', nameEn: 'As Said' },
      { id: 'bayhan', nameAr: 'بيحان', nameEn: 'Bayhan' },
      { id: 'dhar', nameAr: 'دهر', nameEn: 'Dhar' },
      { id: 'habban', nameAr: 'حبان', nameEn: 'Habban' },
      { id: 'hatib', nameAr: 'حطيب', nameEn: 'Hatib' },
      { id: 'jardan', nameAr: 'جردان', nameEn: 'Jardan' },
      { id: 'mayfaah', nameAr: 'ميفعة', nameEn: 'Mayfaah' },
      { id: 'merkhah_al_ulya', nameAr: 'مرخة العليا', nameEn: 'Merkhah Al Ulya' },
      { id: 'merkhah_as_sufla', nameAr: 'مرخة السفلى', nameEn: 'Merkhah As Sufla' },
      { id: 'nisab', nameAr: 'نصاب', nameEn: 'Nisab' },
      { id: 'rudum', nameAr: 'رضوم', nameEn: 'Rudum' },
      { id: 'usaylan', nameAr: 'عسيلان', nameEn: 'Usaylan' }
    ]
  },
  {
    id: 'al_mahrah',
    nameAr: 'المهرة',
    nameEn: 'Al Mahrah',
    districts: [
      { id: 'al_ghaydah', nameAr: 'الغيضة', nameEn: 'Al Ghaydah' },
      { id: 'al_masilah', nameAr: 'المسيلة', nameEn: 'Al Masilah' },
      { id: 'hat', nameAr: 'حات', nameEn: 'Hat' },
      { id: 'hawf', nameAr: 'حوف', nameEn: 'Hawf' },
      { id: 'huswain', nameAr: 'حصوين', nameEn: 'Huswain' },
      { id: 'manar', nameAr: 'منعر', nameEn: 'Manar' },
      { id: 'qishn', nameAr: 'قشن', nameEn: 'Qishn' },
      { id: 'sayhut', nameAr: 'سيحوت', nameEn: 'Sayhut' },
      { id: 'shahan', nameAr: 'شحن', nameEn: 'Shahan' }
    ]
  },
  {
    id: 'marib',
    nameAr: 'مأرب',
    nameEn: 'Marib',
    districts: [
      { id: 'marib_city', nameAr: 'مدينة مأرب', nameEn: 'Marib City' },
      { id: 'al_abdiyah', nameAr: 'العبدية', nameEn: 'Al Abdiyah' },
      { id: 'al_jubah', nameAr: 'الجوبة', nameEn: 'Al Jubah' },
      { id: 'bidbadah', nameAr: 'بدبدة', nameEn: 'Bidbadah' },
      { id: 'harib', nameAr: 'حريب', nameEn: 'Harib' },
      { id: 'harib_al_qaramish', nameAr: 'حريب القراميش', nameEn: 'Harib Al Qaramish' },
      { id: 'jabal_murad', nameAr: 'جبل مراد', nameEn: 'Jabal Murad' },
      { id: 'mahliyah', nameAr: 'ماهلية', nameEn: 'Mahliyah' },
      { id: 'majzar', nameAr: 'مجز', nameEn: 'Majzar' },
      { id: 'marib', nameAr: 'مأرب', nameEn: 'Marib' },
      { id: 'medghal', nameAr: 'مدغل', nameEn: 'Medghal' },
      { id: 'raghwan', nameAr: 'رغوان', nameEn: 'Raghwan' },
      { id: 'rahabah', nameAr: 'رحبة', nameEn: 'Rahabah' },
      { id: 'sirwah', nameAr: 'صرواح', nameEn: 'Sirwah' }
    ]
  },
  {
    id: 'al_jawf',
    nameAr: 'الجوف',
    nameEn: 'Al Jawf',
    districts: [
      { id: 'al_hazm', nameAr: 'الحزم', nameEn: 'Al Hazm' },
      { id: 'al_ghayl', nameAr: 'الغيل', nameEn: 'Al Ghayl' },
      { id: 'al_khalq', nameAr: 'الخلق', nameEn: 'Al Khalq' },
      { id: 'al_maslub', nameAr: 'المصلوب', nameEn: 'Al Maslub' },
      { id: 'al_matammah', nameAr: 'المطمة', nameEn: 'Al Matammah' },
      { id: 'al_maton', nameAr: 'المتون', nameEn: 'Al Maton' },
      { id: 'az_zahir', nameAr: 'الزاهر', nameEn: 'Az Zahir' },
      { id: 'bart_al_anan', nameAr: 'برط العنان', nameEn: 'Bart Al Anan' },
      { id: 'khabb_wa_ash_shaaf', nameAr: 'خب والشعف', nameEn: 'Khabb Wa Ash Shaaf' },
      { id: 'kharab_al_marashi', nameAr: 'خراب المراشي', nameEn: 'Kharab Al Marashi' },
      { id: 'rajuzah', nameAr: 'رجوزة', nameEn: 'Rajuzah' }
    ]
  },
  {
    id: 'al_bayda',
    nameAr: 'البيضاء',
    nameEn: 'Al Bayda',
    districts: [
      { id: 'al_bayda_city', nameAr: 'مدينة البيضاء', nameEn: 'Al Bayda City' },
      { id: 'al_bayda', nameAr: 'البيضاء', nameEn: 'Al Bayda' },
      { id: 'al_arsh', nameAr: 'العرش', nameEn: 'Al Arsh' },
      { id: 'al_malagim', nameAr: 'الملاجم', nameEn: 'Al Malagim' },
      { id: 'al_quraishyah', nameAr: 'القرشية', nameEn: 'Al Quraishyah' },
      { id: 'ar_ryashyyah', nameAr: 'الرياشية', nameEn: 'Ar Ryashyyah' },
      { id: 'as_sawadiyah', nameAr: 'السوادية', nameEn: 'As Sawadiyah' },
      { id: 'as_sawmaah', nameAr: 'الصومعة', nameEn: 'As Sawmaah' },
      { id: 'ash_sharyah', nameAr: 'الشرية', nameEn: 'Ash Sharyah' },
      { id: 'at_taffah', nameAr: 'الطفة', nameEn: 'At Taffah' },
      { id: 'az_zahir', nameAr: 'الزاهر', nameEn: 'Az Zahir' },
      { id: 'dhi_naim', nameAr: 'ذي ناعم', nameEn: 'Dhi Naim' },
      { id: 'maswarah', nameAr: 'مسورة', nameEn: 'Maswarah' },
      { id: 'mukayras', nameAr: 'مكيراس', nameEn: 'Mukayras' },
      { id: 'naaman', nameAr: 'نعمان', nameEn: 'Naaman' },
      { id: 'nati', nameAr: 'ناطع', nameEn: 'Nati' },
      { id: 'radaa', nameAr: 'رداع', nameEn: 'Radaa' },
      { id: 'radman_al_awad', nameAr: 'ردمان', nameEn: 'Radman Al Awad' },
      { id: 'sabah', nameAr: 'صباح', nameEn: 'Sabah' },
      { id: 'wald_rabi', nameAr: 'ولد ربيع', nameEn: 'Wald Rabi' }
    ]
  },
  {
    id: 'raymah',
    nameAr: 'ريمة',
    nameEn: 'Raymah',
    districts: [
      { id: 'al_jabin', nameAr: 'الجبين', nameEn: 'Al Jabin' },
      { id: 'al_jafariyah', nameAr: 'الجعفرية', nameEn: 'Al Jafariyah' },
      { id: 'as_salafiyah', nameAr: 'السلفية', nameEn: 'As Salafiyah' },
      { id: 'bilad_at_taam', nameAr: 'بلاد الطعام', nameEn: 'Bilad At Taam' },
      { id: 'kusmah', nameAr: 'كسمة', nameEn: 'Kusmah' },
      { id: 'mazhar', nameAr: 'مزهر', nameEn: 'Mazhar' }
    ]
  },
  {
    id: 'socotra',
    nameAr: 'سقطرى',
    nameEn: 'Socotra',
    districts: [
      { id: 'hadibu', nameAr: 'حديبو', nameEn: 'Hadibu' },
      { id: 'qalansiyah_wa_abd_al_kuri', nameAr: 'قلنسية وعبد الكوري', nameEn: 'Qalansiyah Wa Abd Al Kuri' }
    ]
  }
];
